<?php

namespace App\Repositories\Production;


use App\Models\PermissionUser;
use App\Repositories\PermissionUserRepositoryInterface;

class PermissionUserRepository extends BaseRepository implements PermissionUserRepositoryInterface
{
    public function __construct(PermissionUser $model)
    {
        parent::__construct($model);
    }

    public function buildQueryByFilter($query, $filter)
    {
        if(array_key_exists('user_id',$filter)) {
            if(!empty($filter['user_id'])) {
                $userID = $filter['user_id'];
                $query = $query->where('user_id', $userID);
            }
            unset($filter['user_id']);
        }

        return parent::buildQueryByFilter($query, $filter); // TODO: Change the autogenerated stub
    }
}
