<?php

namespace App\Repositories\Production;


use App\Repositories\UserRepositoryInterface;
use App\User;

class UserRepository extends BaseRepository implements UserRepositoryInterface
{
    public function __construct(User $model)
    {
        parent::__construct($model);
    }

    public function buildQueryByFilter($query, $filter)
    {
        if(array_key_exists('query',$filter)) {
            if(!empty($filter['query'])) {
                $keywork = $filter['query'];
                $query = $query->where('email', 'LIKE', "%{$keywork}%");
            }
            unset($filter['query']);
        }

        if(array_key_exists('type',$filter)) {
            if(!empty($filter['type'])) {
                $keywork = $filter['type'];
                $query = $query->where('type', $keywork);
            }
            unset($filter['query']);
        }

        
        return parent::buildQueryByFilter($query, $filter); // TODO: Change the autogenerated stub
    }

}
