<?php

namespace App\Repositories\Production;


use App\Models\RoleUser;
use App\Repositories\UserRoleRepositoryInterface;

class UserRoleRepository extends BaseRepository implements UserRoleRepositoryInterface
{
    public function __construct(RoleUser $model)
    {
        parent::__construct($model);
    }

    public function buildQueryByFilter($query, $filter)
    {
        if(array_key_exists('user_id',$filter)) {
            if(!empty($filter['user_id'])) {
                $userID = $filter['user_id'];
                $query = $query->where('user_id', $userID);
            }
            unset($filter['user_id']);
        }

        return parent::buildQueryByFilter($query, $filter); // TODO: Change the autogenerated stub
    }
}
